import gym
import math
import random
import argparse
import os

from collections import namedtuple, deque
from itertools import count

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import torch.onnx
import onnx
import statistics
import matplotlib.pyplot as plt
from torch.nn import Parameter
from mlagents_envs.environment import UnityEnvironment
from mlagents_envs.envs.unity_gym_env import UnityToGymWrapper
from torch.utils.tensorboard import SummaryWriter

writer = SummaryWriter()

# Parse inputs:
parser = argparse.ArgumentParser(description="Parse model behavior")
parser.add_argument("--inference", action="store_true", help="Flag to choose behavior of the last trained model.")
parser.add_argument("--modelname", type=str, help="Name of .pth file for inference")
parser.add_argument("--environment", type=str, help="Name of builded environment folder")
parser.add_argument("--n256", action="store_true", help="Flag for 256 neurons per layer (Second Environment).")
parser.add_argument("--num", type=int, default=500, help="Number of episodes in training.")
args = parser.parse_args()

""" Export the builded Unity environment
to a gym environment using GymWrapper
"""
unity_env = UnityEnvironment(os.getcwd() + '\\' + args.environment)  # RandomPathDQN , EnvB_DQN29
env = UnityToGymWrapper(unity_env, uint8_visual=False, allow_multiple_obs=False)


""" Initialize device to compute tensor calculations
(CPU used) and the rest of the parameters of the DQN algorithm"""

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

Transition = namedtuple('Transition', ('state', 'action', 'next_state', 'reward'))

""" Choose num of episodes according to the device.
Default is 500 for both."""

if torch.cuda.is_available():
    num_episodes = args.num
else:
    num_episodes = args.num


# Hyper parameters: batch size, discount factor, eps-greedy, target network update, learning rate
BATCH_SIZE = 128
GAMMA = 0.99
EPS_START = 0.9
EPS_END = 0.05
EPS_DECAY = 1000
TAU = 0.005
LR = 1e-4


n_actions = env.action_space.n
state = env.reset()
n_observations = len(state)


# Replay memory
class ReplayMemory(object):
    def __init__(self, capacity):
        self.memory = deque([], maxlen=capacity)

    def push(self, *args):
        self.memory.append(Transition(*args))

    def sample(self, batch_size):
        return random.sample(self.memory, batch_size)

    def __len__(self):
        return len(self.memory)


# Neural network using ReLU activation functions and 2 hidden layers.
# neurons per layer: npl
if(args.n256):
    npl = 256
else:
    npl = 128


class DQN(nn.Module):

    def __init__(self, n_observations, n_actions):
        super(DQN, self).__init__()
        self.layer1 = nn.Linear(n_observations, npl)
        self.layer2 = nn.Linear(npl, npl)
        self.layer3 = nn.Linear(npl, npl)
        self.layer4 = nn.Linear(npl, n_actions)

    def forward(self, x):
        x = F.relu(self.layer1(x))
        x = F.relu(self.layer2(x))
        x = F.relu(self.layer3(x))
        return self.layer4(x)


policy_net = None
target_net = None
policy_net = DQN(n_observations, n_actions).to(device)
target_net = DQN(n_observations, n_actions).to(device)

model = DQN(n_observations, n_actions).to(device)

target_net.load_state_dict(policy_net.state_dict())

# Initialize AdamW optimizer: a gradient-descent-based method using weight regularization
optimizer = optim.AdamW(policy_net.parameters(), lr=LR, amsgrad=True)
memory = ReplayMemory(10000)

steps_done = 0

"""WrapperNet is used to export the .onnx file in a form compatible with
ML-Agents (2.0.1) Brains. The form must match the .onnx files generated by
the default ML-Agents trainers."""


class WrapperNet(torch.nn.Module):
    def __init__(
            self,
            policy_net: DQN,
            discrete_output_sizes: [int],
    ):
        """
        Wraps the network adding extra constants and dummy mask inputs
        required by runtime inference with Sentis.

        For environments with continuous actions, outputs would need to be
        added similarly to how discrete action outputs work, both in the
        wrapper and in the ONNX output_names / dynamic_axes.
        """
        super(WrapperNet, self).__init__()
        self.policy_net = policy_net

        version_number = torch.Tensor([3])
        self.version_number = Parameter(version_number, requires_grad=False)

        memory_size = torch.Tensor([0])
        self.memory_size = Parameter(memory_size, requires_grad=False)

        output_shape = torch.Tensor([discrete_output_sizes])
        self.discrete_shape = Parameter(output_shape, requires_grad=False)

    # For discrete actions ML-Agents expects a corresponding mask tensor
    # with the same shape to exist as input.
    def forward(self, visual_obs: torch.tensor, mask: torch.tensor):
        qnet_result = self.policy_net(visual_obs)
        # Connect mask to keep it from getting pruned.
        # Mask values will be 1 if you never call SetActionMask() in
        # WriteDiscreteActionMask()
        qnet_result = torch.mul(qnet_result, mask)
        action = torch.argmax(qnet_result, dim=1, keepdim=True)
        return [action], self.discrete_shape, self.version_number, self.memory_size


"""Save the reward plot to the writer. writer.add_figure adds the plot to
tensorboard."""


def plot_reward(plot_episode_array, plot_reward_array):
    fig = plt.figure(figsize=(8, 6))
    plot_episode_array0 = []
    temp_ar = []
    perTen_episodes = list(range(0, int(num_episodes/10) + 1))
    c = 0
    for i in plot_reward_array:
        c = c + 1
        temp_ar.append(i)
        if(c % 10 == 0):
            plot_episode_array0.append(statistics.mean(temp_ar))
            temp_ar = []

    plt.plot(plot_episode_array, plot_reward_array, linestyle='-')
    plt.title('Reward per Episode')
    plt.xlabel('Episodes')
    plt.ylabel('Rewards')
    plt.grid(True)
    plt.savefig('rew_plot.png')
    writer.add_figure("Rewards per Episode", fig)
    writer.flush()
    writer.close()


"""
Select action using an eps-greedy policy.
Exploration to exploitation.
"""


def select_action(state):
    global steps_done
    sample = random.random()
    eps_threshold = EPS_END + (EPS_START - EPS_END) * \
        math.exp(-1 * steps_done / EPS_DECAY)
    steps_done += 1
    if sample > eps_threshold:
        with torch.no_grad():
            return policy_net(state).max(1).indices.view(1, 1)
    else:  # Choose random action:
        return torch.tensor([[env.action_space.sample()]], device=device, dtype=torch.long)


""" Save the trained model to an .onnx file which can be transferred to a
Unity project (Behavior Parameters > Model) and run in inference in a Unity
application. The form must match the .onnx files generated by the default
ML-Agents trainers."""


def save_model_onnx():
    example_inp = torch.randn(1, n_observations)

    torch.onnx.export(
        WrapperNet(policy_net, [n_actions]),
        # A tuple with an example of the input tensors
        (example_inp, torch.ones(1, n_actions)),
        'model.onnx',
        opset_version=9,
        # input_names must correspond to the WrapperNet forward parameters
        input_names=["obs_0", "action_masks"],
        # output_names must correspond to the return tuple of the WrapperNet
        # forward function.
        output_names=["discrete_actions", "discrete_action_output_shape",
                      "version_number", "memory_size"],
        # All inputs and outputs should have their 0th dimension designated
        # as 'batch'
        dynamic_axes={'obs_0': {0: 'batch'},
                      'action_masks': {0: 'batch'},
                      'discrete_actions': {0: 'batch'},
                      'discrete_action_output_shape': {0: 'batch'},
                      }
    )


"""OPTIMIZE:"""


def optimize_model(i_episode):
    if len(memory) < BATCH_SIZE:
        return
    """Sample a batch from memory and create a batch variable as a dict with
     categories: batch[0] -> states, batch[1] -> actions, batch[2] -> next_state, batch[3] -> reward"""
    transitions = memory.sample(BATCH_SIZE)
    batch = Transition(*zip(*transitions))

    """Find final and non-final next states from our batch of size 128."""
    non_final_mask = torch.tensor(tuple(map(lambda s: s is not None, batch.next_state)), device=device, dtype=torch.bool)
    non_final_next_states = torch.cat([s for s in batch.next_state if s is not None])

    """Make our data a 1-column tensor for state, action, reward."""
    state_batch = torch.cat(batch.state)
    action_batch = torch.cat(batch.action)
    reward_batch = torch.cat(batch.reward)

    """
    Calculate our policy max Q(s,a,z) and target max Q(s,a,z')
    (estimated optimal Q) and compute the loss function using Huber Loss.

    After that we continue by computing gradients and performing
    backpropagation to make an optimization step and update the weights of
    our policy network according to the direction of the gradients.
    """
    state_action_values = policy_net(state_batch).gather(1, action_batch)  # gathers actions received from agent.

    next_state_values = torch.zeros(BATCH_SIZE, device=device)

    with torch.no_grad():
        next_state_values[non_final_mask] = target_net(non_final_next_states).max(1).values

    expected_state_action_values = (next_state_values * GAMMA) + reward_batch

    criterion = nn.SmoothL1Loss()
    loss = criterion(state_action_values, expected_state_action_values.unsqueeze(1))

    writer.add_scalar("loss/training", loss, i_episode)

    optimizer.zero_grad()
    loss.backward()

    torch.nn.utils.clip_grad_value_(policy_net.parameters(), 100)
    optimizer.step()


"""
Inference loop: use the trained model to evaluate the agent's behavior.
It also prints the last policy in the terminal to test whether the agent
converges to a rational policy.
"""


def inference_loop(model):
    inf_policy = []
    for i_episode in range(20):
        inf_policy = []
        state = env.reset()
        state = torch.tensor(state, dtype=torch.float32, device=device).unsqueeze(0)

        for t in count():
            action = model(state).max(1).indices.view(1, 1)
            observation, reward, terminated, info = env.step(action.item())
            reward = torch.tensor([reward], device=device)
            done = terminated

            if terminated:
                next_state = None
            else:
                inf_policy.append(action)
                next_state = torch.tensor(observation, dtype=torch.float32, device=device).unsqueeze(0)

            state = next_state

            if done:
                break
    print(inf_policy)


""" Main training loop: """


def training_loop():
    plot_reward_array = []
    plot_episode_array = []
    temp_rewards = []

    for i_episode in range(num_episodes):

        # init environment and get state. Convert state to a tensor and add a dimension for tensor operations
        state = env.reset()
        state = torch.tensor(state, dtype=torch.float32, device=device).unsqueeze(0)  # shape (1, n_observations)

        for t in count():
            action = select_action(state)
            # Make a step using the action returned from the eps-greedy policy and collect state, reward of next state
            observation, reward, terminated, info = env.step(action.item())

            temp_rewards.append(reward)  # For plot

            # Reward as tensor to use it in optimizer
            reward = torch.tensor([reward], device=device)
            done = terminated

            # Check if episode terminates:
            if terminated:
                next_state = None
            else:
                next_state = torch.tensor(observation, dtype=torch.float32, device=device).unsqueeze(0)

            """ Save our data as tensors in memory """
            memory.push(state, action, next_state, reward)
            state = next_state

            optimize_model(i_episode)

            target_net_state_dict = target_net.state_dict()
            policy_net_state_dict = policy_net.state_dict()

            """Slowly update our target network"""
            for key in policy_net_state_dict:
                target_net_state_dict[key] = policy_net_state_dict[key] * TAU + target_net_state_dict[key] * (1 - TAU)
            target_net.load_state_dict(target_net_state_dict)

            if done:
                print(f"Episode {i_episode}/{num_episodes}.")
                break

        # for plot:
        plot_reward_array.append(statistics.mean(temp_rewards))
        plot_episode_array.append(i_episode)
        temp_rewards = []
    writer.flush()

    print("Completed .. ")
    # Save model as .onnx file (for Unity)
    save_model_onnx()
    print(f".onnx model saved at {os.getcwd()}\\model.onnx")
    # Save model as dict for local usage
    torch.save(policy_net, os.getcwd()+'\\model.pth')
    print(f"model saved as .pth : {os.getcwd()}\\model.pth")
    plot_reward(plot_episode_array, plot_reward_array)


def main(args):

    if(args.inference):
        print("Loading last trained model..")

        # Load our last trained model from a .pth file
        model = torch.load(os.getcwd() + '\\' + args.modelname)
        print(f"Model : {model}. Loaded")
        # Do not use grads
        model.eval()
        inference_loop(model)
    else:
        training_loop()


if __name__ == "__main__":
    main(args)
